sudo: false

language: node_js
node_js: "8.11.4"

os:
  - linux

env:
  matrix:
    - ELM_VERSION=0.19.1

before_install:
  - npm i -g npm@lts
  - npm i -g elm@latest-0.19.1
  - npm i -g npm@6.4.1
  - npm i -g elm-format@0.8.3

install:
  - npm ci

script:
  - echo '$TRAVIS_TAG is ' $TRAVIS_TAG
  - npm test
  - ./bin/approve
  - cd examples/subscription/ && npm ci && npm run build && cd ../..

deploy:
  - provider: npm
    email: dillon@dillonkearns.com
    api_key: $NPM_TOKEN
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_TAG =~ ^v
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: examples/subscription/dist
    on:
      branch: master
